name: Update data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '23 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Python requirements
      run: |-
        python -m pip install -U pip
        pip install -r requirements.txt
    - name: Update news
      run: |-
        ./scrape_news.py
    - name: Generate HTML
      run: |-
        ./generate_html.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest update: ${timestamp}" || exit 0
        git push
